### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane "starter package" as discussed in #2

### CODE REVIEW

**Comment by IzzySoft** [comment]
PS: Be welcome to add the screenshots to `fastlane/metadata/android/en-US/images/phoneScreenshots/`. You can btw also use the Fastlane binaries to deploy to Google Play if you wish. Or to maintain fastlane data (it e.g. allows to automate screenshot creation and some more).

**Comment by IzzySoft** [comment]
@wellenvogel any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by wellenvogel** [comment]
I will try to address this within this year. Currently I'm busy with my other app...

**Comment by wellenvogel** [comment]
Ok, did the merge. But for my side I will not really use the fastlane stuff...
Would you still trigger the RFP?

**Comment by IzzySoft** [comment]
> Ok, did the merge.

Thanks!

> But for my side I will not really use the fastlane stuff...

Guess you rarely have to touch it anyway. Basically only if description needs to be updated.

> Would you still trigger the RFP?

Can do – once you've tagged the next release (fastlane is looked for at the tag the APK was built from). Just give me a ping then (e.g. here, or from the linked issue), and I'll open an RFP for you. Question in advance: can I count on your help should there be issues with the build process? Not that I expect any, but just in case. Because if I can, I might even be able to do the inclusion for you (not just requesting it).

**Comment by wellenvogel** [comment]
I would be willing to help - sure.
OK - do we really need a next release? Would potentially confuse people a bit (current users) - it's considered very bad practice to have a release without any features/fixes. Of course I could increase the version without delivering to play store.

What about the signing keys? Currently nobody else would be able to build a signed release version as the keys are not available...

**Comment by IzzySoft** [comment]
> I would be willing to help - sure.

Great! Then I'm in.

> do we really need a next release?

Well, we need a tag at which Fastlane is available. Just a tag suffices – no deploy to Play Store needed, not even a "release" (in the sense of "tag with release notes"). Just the tag name must have the pattern you will follow in the future. So yes, increasing the version without delivering to play is totally fine.

Let me check: Currently, your tag names follow the pattern `release-<versionCode>`. Your `versionCode` follows the rule of `major * 100 + minor`. So maybe adjust `build.gradle` to

```gradle
        versionCode 106
        versionName "1.6"
```

commit that and then `git tag release-106` – without deploying to play? That done, I'd set up the RFP for you and, once that "confirmed ready", go on for the corresponding merge request against fdroiddata (that's the part where I might need your help, should e.g. the build run into issues). I'm confident that succeeds, and we've got your app into F-Droid within a week (ha! now that I'm "junior packager" I got quite bold :rofl:).

> What about the signing keys?

Those remain with F-Droid. Like you, we don't hand them out to others. Oh: we sign with our own, created and maintained on an air-gapped machine. Of course a separate key for each app. But yeah, cross-updates won't be possible – unless you want to go for "reproducible builds" (which would be some extra effort and not necessarily easy), in which case on success F-Droid takes the APK you've signed and adds their signature on top.

**Comment by wellenvogel** [comment]
Ok, just updated to 106, added the release tag.
Are the changelog infos mandatory? - Currently I did not provide any...
Having the signing keys at FDROID is completely fine to me. I think cross updates are no issue at all - either people go for PlayStore or FDROID...

**Comment by IzzySoft** [comment]
> Ok, just updated to 106, added the release tag.

Thanks! Will look into opening the RFP ASAP.

> Are the changelog infos mandatory?

No. short- and full-description are mandatory. Icon and screenshots are highly recommended. Per-release changelogs are recommended, FeatureGraphic is nice-to-have – all else is purely optional.

> Having the signing keys at FDROID is completely fine to me. I think cross updates are no issue at all - either people go for PlayStore or FDROID...

Full ack. Again, reproducible-builds are a good goal to ascribe to – but the difficulties reaching that are not to be underestimated, from what I see (like NewPipe being not updated for weeks now because it hangs at exactly that stage: builds fine but comparison fails due to some technical stuff).

**Comment by IzzySoft** [comment]
OK, [here you go](https://gitlab.com/fdroid/rfp/-/issues/1599). Even self-assigned it. I'll add a little promotion on top: this will be the candidate for my next training session for aspiring new F-Droid reviewers :smiley:

**Comment by wellenvogel** [comment]
Cool. Many thanks.
Btw: Have a nice christmas...

**Comment by IzzySoft** [comment]
Thanks – for you, too!

**Comment by IzzySoft** [comment]
I either got bold or sly: now that the RFP went through so fine (thanks to your preparation), I went ahead and [opened the corresponding merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7974). Keep your :crossed_fingers: it works as fine as well! That would be my first full run then (from opening the RFP to merging the YAML). I'd love that :smile:

**Comment by wellenvogel** [comment]
Looks great.
Will keep fingers crossed.

**Comment by IzzySoft** [comment]
Merged, all pipelines succeeded – with some luck it shows up at F-Droid before 2020 is out! Looks like a full success, I'm proud of myself :smile:

Shall I still keep it in my repo then, once it shows up at F-Droid.org? Some background on this question [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

Btw: funnily, BonjourBrowser didn't detect a single service in my house… Oh, **exactly now** it finds the one I was waiting it would report! Well, so make that: "…until I complain to you" :rofl: It just found my printer. But shouldn't it also find my regular web servers (Apache) running on default ports (80,443)? Well, maybe I just let it run a little longer. Though if it goes by IP from 1 to 254, it should have found the Apache first… Now I'm curious, and just let it run until it says done :laughing:

Thanks!

**Comment by wellenvogel** [comment]
> Shall I still keep it in my repo then, once it shows up at F-Droid.org?
For me this does not really matter - I would leave this to you.

Is there anything I would need to do for further releases?

For the found services:
The app is just discovering what is announced by bonjour/avahi/zeroconf. A simple web server will typically not do this (you explicitly have to announce your service...).
For the discovery itself there is not too much I can do. I just have to rely on the Android APIs - and they are .... hmm - at least not perfect.
Under the hood this is multicast - but then there is a couple of software layers above - and some of them have own ideas.
I also sometimes notice long detection times - it could even be faster to kill the app and restart.

**Comment by IzzySoft** [comment]
> For me this does not really matter - I would leave this to you.

OK, if it doesn't matter the default is I remove it once it "settled" in the main repo (which usually means 7..10 days overlap).

> Is there anything I would need to do for further releases?

Keep on tagging after increasing `versionCode` and adjusting `versionName` should do :smile:

> For the found services:

Thanks, that explains. Funny, though, that it found my printer an hour ago (I couldn't check what it says about it as I had to heed a different task) – and though I kept scan on, it disappeared again. So after 2h of scanning, the list is still (or again) empty.

> it could even be faster to kill the app and restart.

Ah! That: stop -> start -> printer is back. And it was lost due to the WiFi bug hitting that device again ("connected, no internet" => "have you tried turning it off and on again?" => OK :zany_face:)

Thanks again! Maybe some of those details should go to the app's description in fastlane? If you need the German translation then (which I somehow doubt, assuming you're a German native speaker) I gladly assist.

**Comment by wellenvogel** [comment]
> Thanks again! Maybe some of those details should go to the app's description in fastlane? If you need the German translation then (which I somehow doubt, assuming you're a German native speaker) I gladly assist.

:-) Yes, maybe I could add a bit with the next version. And german should be easy ... although - funny enough - I often start writing things in english.

**Comment by IzzySoft** [comment]
> I often start writing things in english.

Hehe… sounds familiar to me :rofl:

**Comment by wellenvogel** [comment]
Just saw the app on f-droid. Great...
Is there a chance to see how many downloads it has?

**Comment by IzzySoft** [comment]
No chance. For privacy reasons, no logs are kept, so there are almost no ways for any stats. Though it was discussed more than once (like, "anonymous" stats by shortening/hashing/removing IPs), there was never a consensus reached so it stayed the most privacy friendly way: data that's not available cannot be abused :wink:

**Comment by wellenvogel** [comment]
Hi,
just updated to a new version.
Anything still to be done to make it visible at F-Droid?
I saw some commit with 107 in the metadata - but still the older version is there for download.

**Comment by IzzySoft** [comment]
> just updated to a new version.

Just will take a little to be picked up. 5h is to short, but 5d should not be exceeded :rofl:

Our updater just found r107 a few ours ago and added it, so that should show up soon. r109 should be detected on its next run, so maybe both are even added at the same time – depending on when the build cycle cycles.

You saw what CheckUpdates added, yes. After that it must be built, though. And a build cycle usually takes around 36h, then APKs must be signed and a fresh index needs to be published – so it's rather around 2d+

**Comment by wellenvogel** [comment]
Ok, good to know.
So I will wait patiently...

**Comment by wellenvogel** [comment]
Hmm, starting to wonder a bit... still 106 after 5 days

**Comment by IzzySoft** [comment]
[109 was built successfully](https://monitor.f-droid.org/builds/log/de.wellenvogel.bonjourbrowser/109) yesterday and should hopefully come with the next index deployment. And for the cat, ahem, curiosity: You can always watch [the running build cycle](https://monitor.f-droid.org/builds/running) :wink:

**Comment by wellenvogel** [comment]
Ok. But strange enough I saw the build of 107 already some days ago - but still it is not in the index.

**Comment by IzzySoft** [comment]
It was in the same build cycle. As a new index was just published today… Well, there it is. But now without summary, description or screenshots :scream:

Argh… you've triggered ***that*** bug. Please move those changelog files (`107.txt`, `109.txt`) to where they belong: into a sub-directory called `changelogs`.

**Pull request merged**
